version: '3.8'

services:
  nextjs:
    build: .
    ports:
      - '3000:3000'
    environment:
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}

  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080" # Web interface
      - "1025:1025" # SMTP server
